### ISSUE TITLE
Missing empty spaces in if statement

### ISSUE THREAD

**Issue by Xenotech81** [thakkaryash94/docker-postgres-backup#1]
Hi Thakkaryash,
I just tried out your repo by building it myself with Docker and triggering backup.sh manually inside the container. The shell complained about missing spaces in the if statement (but the script ran through).

The issue is in :
https://github.com/thakkaryash94/docker-postgres-backup/blob/b2c58e5f506e59907e16dc40a1c42541df9579ad/backup.sh#L15

Adding empty spaces solved the problem:
`if [ -z "$S3_BUCKET" ] || [ -z "$S3_ACCESS_KEY" ] || [ -z "$S3_SECRET_KEY" ]; then`

I am not really familiar with shell, but [this blog ](https://acloudguru.com/blog/engineering/conditions-in-bash-scripting-if-statements?utm_source=legacyla&utm_medium=redirect&utm_campaign=one_platform)says sh always expects empty spaces.

Regards

**Comment by thakkaryash94** [comment]
Hey @Xenotech81 , I agree. Thank you for the issue and for finding the fix as well. I have updated the code. It's fixed and docker image is updated as well.
